from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, update

from typing import List
from pydantic import BaseModel
import anyio

from app.db.session import get_db
from app.models.course_models import Lesson as LessonModel
from app.schemas.course import LessonOut

router = APIRouter()


class QuizQuestionOut(BaseModel):
    id: int
    question: str
    type: str = "multiple_choice"  # "multiple_choice", "true_false", "short_answer"
    options: List[str] = []
    answerIndex: int = 0
    correctAnswer: str = ""
    explanation: str


class QuizOut(BaseModel):
    questions: List[QuizQuestionOut]


@router.get("/lessons/{lesson_id}/quiz", response_model=QuizOut)
async def get_lesson_quiz(lesson_id: str, db: AsyncSession = Depends(get_db)):
    stmt = select(LessonModel).where(LessonModel.id == lesson_id)
    res = await db.execute(stmt)
    lesson = res.scalars().first()
    if not lesson:
        raise HTTPException(status_code=404, detail="Lesson not found")

    if not lesson.content or not lesson.content.strip():
        return QuizOut(questions=[])

    # Generate quiz using LLMClient
    from app.common.llm_client import LLMClient
    llm = LLMClient()

    system_prompt = (
        "You are an expert educational assessment creator. Generate a 3-question practice quiz based strictly on the provided lesson text.\n"
        "The quiz MUST include a diverse mix of question types:\n"
        "1. Multiple Choice (type: 'multiple_choice') with 4 options, 'answerIndex' (0-3), and 'correctAnswer'\n"
        "2. True/False (type: 'true_false') with options ['True', 'False'], 'answerIndex' (0 or 1), and 'correctAnswer'\n"
        "3. Short Answer (type: 'short_answer') with 'correctAnswer' (concise string answer) and empty options list []\n"
        "Your response MUST be a JSON object with a single 'questions' list matching this JSON structure:\n"
        "{\n"
        "  \"questions\": [\n"
        "    {\n"
        "      \"id\": 1,\n"
        "      \"type\": \"multiple_choice\",\n"
        "      \"question\": \"Which factor primary determines...\",\n"
        "      \"options\": [\"Option A\", \"Option B\", \"Option C\", \"Option D\"],\n"
        "      \"answerIndex\": 1,\n"
        "      \"correctAnswer\": \"Option B\",\n"
        "      \"explanation\": \"Detailed explanation of why this answer is correct.\"\n"
        "    },\n"
        "    {\n"
        "      \"id\": 2,\n"
        "      \"type\": \"true_false\",\n"
        "      \"question\": \"Statement to evaluate as True or False.\",\n"
        "      \"options\": [\"True\", \"False\"],\n"
        "      \"answerIndex\": 0,\n"
        "      \"correctAnswer\": \"True\",\n"
        "      \"explanation\": \"Detailed explanation.\"\n"
        "    },\n"
        "    {\n"
        "      \"id\": 3,\n"
        "      \"type\": \"short_answer\",\n"
        "      \"question\": \"What term describes...?\",\n"
        "      \"options\": [],\n"
        "      \"answerIndex\": 0,\n"
        "      \"correctAnswer\": \"Canonical short answer\",\n"
        "      \"explanation\": \"Detailed explanation.\"\n"
        "    }\n"
        "  ]\n"
        "}\n"
        "Ensure all questions are strictly derived from the lesson text."
    )

    user_prompt = f"Lesson Title: {lesson.title}\n\nLesson Content:\n{lesson.content}"

    try:
        # Run blocking HTTP request in a thread pool
        quiz_data = await anyio.to_thread.run_sync(llm.complete_json, system_prompt, user_prompt)
        
        if not isinstance(quiz_data, dict) or "questions" not in quiz_data:
            raise HTTPException(status_code=500, detail="Invalid quiz format generated by AI")

        # Normalize IDs and fallback fields
        for i, q in enumerate(quiz_data["questions"]):
            q["id"] = i + 1
            if "type" not in q:
                q["type"] = "multiple_choice"
            if "options" not in q:
                q["options"] = []
            if "answerIndex" not in q:
                q["answerIndex"] = 0
            if "correctAnswer" not in q:
                if q.get("options") and len(q["options"]) > q.get("answerIndex", 0):
                    q["correctAnswer"] = q["options"][q["answerIndex"]]
                else:
                    q["correctAnswer"] = ""

        return QuizOut(questions=quiz_data["questions"])
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to generate quiz: {str(e)}")


from sqlalchemy.orm import selectinload

@router.get("/lessons/{lesson_id}", response_model=LessonOut)
async def get_lesson(lesson_id: str, db: AsyncSession = Depends(get_db)):
    stmt = select(LessonModel).options(selectinload(LessonModel.chapter)).where(LessonModel.id == lesson_id)
    res = await db.execute(stmt)
    lesson = res.scalars().first()
    if not lesson:
        raise HTTPException(status_code=404, detail="Lesson not found")
    course_id = lesson.chapter.course_id if lesson.chapter else None
    return LessonOut(
        id=lesson.id,
        title=lesson.title,
        content=lesson.content,
        examples=lesson.examples,
        key_takeaways=lesson.key_takeaways,
        summary=lesson.summary,
        position=lesson.position,
        course_id=course_id,
    )


@router.patch("/lessons/{lesson_id}/complete")
async def complete_lesson(lesson_id: str, db: AsyncSession = Depends(get_db)):
    stmt = select(LessonModel).where(LessonModel.id == lesson_id)
    res = await db.execute(stmt)
    lesson = res.scalars().first()
    if not lesson:
        raise HTTPException(status_code=404, detail="Lesson not found")
    # toggle completion
    lesson.is_completed = 1
    await db.commit()
    return {"lesson_id": lesson.id, "completed": True}
