from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, update

from typing import List
from pydantic import BaseModel
import anyio

from app.db.session import get_db
from app.models.course_models import Lesson as LessonModel
from app.schemas.course import LessonOut

router = APIRouter()


class QuizQuestionOut(BaseModel):
    id: int
    question: str
    options: List[str]
    answerIndex: int
    explanation: str


class QuizOut(BaseModel):
    questions: List[QuizQuestionOut]


@router.get("/lessons/{lesson_id}/quiz", response_model=QuizOut)
async def get_lesson_quiz(lesson_id: str, db: AsyncSession = Depends(get_db)):
    stmt = select(LessonModel).where(LessonModel.id == lesson_id)
    res = await db.execute(stmt)
    lesson = res.scalars().first()
    if not lesson:
        raise HTTPException(status_code=404, detail="Lesson not found")

    if not lesson.content or not lesson.content.strip():
        return QuizOut(questions=[])

    # Generate quiz using LLMClient
    from app.common.llm_client import LLMClient
    llm = LLMClient()

    system_prompt = (
        "You are an expert educational tutor. Generate a short 3-question multiple choice quiz based strictly on the provided lesson text.\n"
        "Your response must be a JSON object with a single 'questions' list matching this JSON structure:\n"
        "{\n"
        "  \"questions\": [\n"
        "    {\n"
        "      \"id\": 1,\n"
        "      \"question\": \"Question text?\",\n"
        "      \"options\": [\"Option 0\", \"Option 1\", \"Option 2\", \"Option 3\"],\n"
        "      \"answerIndex\": 1,\n"
        "      \"explanation\": \"Detailed explanation of why this answer is correct.\"\n"
        "    }\n"
        "  ]\n"
        "}\n"
        "Ensure all questions are strictly derived from the lesson facts. Do not make up outside facts."
    )

    user_prompt = f"Lesson Title: {lesson.title}\n\nLesson Content:\n{lesson.content}"

    try:
        # Run blocking HTTP request in a thread pool to avoid blocking the event loop
        quiz_data = await anyio.to_thread.run_sync(llm.complete_json, system_prompt, user_prompt)
        
        if not isinstance(quiz_data, dict) or "questions" not in quiz_data:
            raise HTTPException(status_code=500, detail="Invalid quiz format generated by AI")

        # Normalize IDs
        for i, q in enumerate(quiz_data["questions"]):
            q["id"] = i + 1

        return QuizOut(questions=quiz_data["questions"])
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to generate quiz: {str(e)}")


@router.get("/lessons/{lesson_id}", response_model=LessonOut)
async def get_lesson(lesson_id: str, db: AsyncSession = Depends(get_db)):
    stmt = select(LessonModel).where(LessonModel.id == lesson_id)
    res = await db.execute(stmt)
    lesson = res.scalars().first()
    if not lesson:
        raise HTTPException(status_code=404, detail="Lesson not found")
    return LessonOut(
        id=lesson.id,
        title=lesson.title,
        content=lesson.content,
        examples=lesson.examples,
        key_takeaways=lesson.key_takeaways,
        summary=lesson.summary,
        position=lesson.position,
    )


@router.patch("/lessons/{lesson_id}/complete")
async def complete_lesson(lesson_id: str, db: AsyncSession = Depends(get_db)):
    stmt = select(LessonModel).where(LessonModel.id == lesson_id)
    res = await db.execute(stmt)
    lesson = res.scalars().first()
    if not lesson:
        raise HTTPException(status_code=404, detail="Lesson not found")
    # toggle completion
    lesson.is_completed = 1
    await db.commit()
    return {"lesson_id": lesson.id, "completed": True}
